### ISSUE TITLE
Handle COMMIT_MSG specially: wrap at 76 columns, strongly suggest short oneline

### ISSUE THREAD

**Issue by dscho** [dscho/notepad.tcl#2]
The best practices state that commit messages should start with a brief oneline, followed by a body after an empty line. The text should be wrapped at <= 76 columns.

As the main purpose of `notepad.tcl` is to provide a user-friendly Git editor (for developers who are unfamiliar with `vim`), we should handle the commit message case first and foremost, and make it easy to follow conventions.

**Comment by dscho** [comment]
@patthoyts I would be willing to tackle this issue, and if you could give me any pointers how to do that, I would be delighted!

**Comment by patthoyts** [comment]
Automatically wrapping might be possible but requires hooking into the insertion and paste functions in the tcl script library functions I reckon. It's also more likely to be annoying. I personally dislike software that types for me so I implemented a marker bar at column 76 instead.

**Comment by dscho** [comment]
> Automatically wrapping might be possible but requires hooking into the insertion and paste functions in the tcl script library functions I reckon. It's also more likely to be annoying. I personally dislike software that types for me so I implemented a marker bar at column 76 instead.

I am way too lazy to wrap the text myself, so I would like to have that option, and since you dislike it, it should be opt-in (but probably remembered via the registry).

Would you have any pointer for me where I can read up on the insertion and paste function hooks?

**Comment by dscho** [comment]
I think I'll just put this to rest, as we now have multiple great options for editors in the Git for Windows installer to choose from.
