### ISSUE TITLE
On MacOSX, the appname is set incorrectly

### ISSUE THREAD

**Issue by dscho** [dscho/notepad.tcl#3]
Unfortunately, starting `notepad.tcl` on MacOSX starts the `Wish` application and it seems that neither `wm title` nor `tk appname` are able to change the name to `Notepad`. Maybe there are some Tcl libraries to help with this?

**Comment by patthoyts** [comment]
I believe this is to do with MacOS X Application Bundles. There is some information on the [Tcl Wiki](http://wiki.tcl.tk/12945) although I don't know how current this might be.

**Comment by dscho** [comment]
Well, I do not use MacOS anymore, so it does not really bother me any longer. Thanks for following up, though!
